version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container_rok
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_rk
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      # choisis un mot de passe sécurisé
      - PGADMIN_CONFIG_SERVER_MODE:="False"
    ports:
      - "5050:80"  # Accès via http://localhost:5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
